### ISSUE TITLE
searchBy and filterBy methods of Table not working as expected

### ISSUE THREAD

**Issue by Inov92** [jdi-testing/jdi-light#2066]
**Issue description:**
@JTable annotation has **filter()** property that by default responsible for search text field above table. Logically method **searchBy** should be responsible for input search query for the table, however from code perspective it the same as **filterBy** that should be responsible for clicking on row header with filter functionality by name. In addition, filter by also not working.

**Steps to reproduce:**
1. Check out branch 2066-searchby-table-issue
2. Launch test io.github.epam.html.tests.elements.complex.table.TableWithPagesTests

**Notes:**
Test based on "Table with pages" page https://jdi-testing.github.io/jdi-light/table-pages.html
Test scenario:
1. Open  "Table with pages" page
2. Filter the table by row "Type"
3. Input to the table search field "Aj"
4. Row with Ajax is shown

**Comment by ViktarR** [comment]
Thank you for your attention and ticket.
Filter by default has property "th input[type=search]", and that field correspond for th tag only.
You are right, logically methods searchBy and filterBy should perform some action, but for some reasons methods return UiElement, with which we can interact, may be it's done because of, some times table can looks like [that](https://demo.umi-cms.spb.su/demos/tableSort/1.html) with selects and other elements. The examle with filters you can find in [branch](https://github.com/jdi-testing/jdi-light/tree/2066_filterBy_test_fix).
This ticket helped to find the problem, you can find it by the [link](https://github.com/jdi-testing/jdi-light/issues/2121)
