### ISSUE TITLE
Fix JDI-Light integration with Sauce Labs in WebSettings

### ISSUE THREAD

**Issue by AkioFaris** [jdi-testing/jdi-light#2100]
Modify WebSettings.getRemoteUrl() to use username, access key from sauceCapabilities() in sauce labs url.
In WebSettings.init() lines
```
            fillAction(p -> DRIVER.remoteUrl = getRemoteUrl(p), "remote.type");
            fillAction(p -> DRIVER.remoteUrl = p, "driver.remote.url");
```
make changes so "driver.remote.url" would not overwrite url from getRemoteUrl(p).

**Comment by gbuh** [comment]
This ticket was raised because of the unstable and sometimes unexpected behavior of the temporary SauceLabs account. After further verification with another account, in my opinion, this action is not necessary.
I checked the workflow and noted that second action actually overwrites the url from getRemoteUrl(p) to the url from the properties if defined. In case the user does not specify "driver.remote.url" property, the framework uses default value from source code.
