### ISSUE TITLE
Create branch for Vuetify

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#3039]
Create a branch for Vuetify
Name it - vuetify-develop
Set protection against delete action

Reference to the Epic - #3036

**Comment by evgenii-liashenko** [comment]
To do: Set protection against delete action.

I have no Settings tab on the main page of the repository:
https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#editing-a-branch-protection-rule
I suggest that either a user with sufficient access rights should set the protection or to grant me access so that I can set the protection myself
