### ISSUE TITLE
fix: imports .*;

### ISSUE THREAD

**Issue by tsvetaevAlex** [jdi-testing/jdi-light#3278]
avoid to use imports .*; to exclude unused import case.

**Comment by tsvetaevAlex** [comment]
PR: #3271 : jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/AvatarTests.java
PR: #3266  : jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/navigation/StepperTests.java
PR #3260  : jdi-light-material-ui-tests/src/main/java/io/github/com/pages/inputs/FloatingActionButtonPage.java
PR #3254 : jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/utils/TransitionTests.java
PR #3252 : jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/SelectTests.java
PR #2868 : jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements/common/CookiesTests.java


*NOTE: may describe an possible issue:
article:https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

**Comment by nechepurenkoN** [comment]
PR: #3271 : jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/AvatarTests.java - fixed by the author
PR: #3266 : jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/navigation/StepperTests.java - fixed by the author
PR #3260 : jdi-light-material-ui-tests/src/main/java/io/github/com/pages/inputs/FloatingActionButtonPage.java - fixed by the author
PR #3254 : jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/utils/TransitionTests.java - fixed in 1c412bf
PR #3252 : jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/SelectTests.java - fixed by the author
PR #2868 : jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements/common/CookiesTests.java - fixed in 67a1e4c

**Comment by nechepurenkoN** [comment]
Also, I replaced all wildcard imports in the `master_material_ui` branch. See: #3280
