### ISSUE TITLE
Update test-site: element select

### ISSUE THREAD

**Issue by annav00** [jdi-testing/jdi-light#4288]
Update test-site: element select:

- [x] append-icon (icon)
- [x] append-outer-icon (y/n)
- [x] autofocus (y/n)
- [x] background-color (name of material color or css color)
- [x] clear-icon (icon)
- [x] theme (dark/light)
- [x] deletable-chips (y/n)
- [x] disable-lookup (y/n)
- [x] error-count (number)
- [x] flat (y/n)
- [x] full-width (y/n)
- [x] height (0-n)
- [x] hide-selected (y/n)
- [x] loader-height (0-n)
- [x] loading (y/n) 
- [x] messages (string)
- [x] no-data-text (string)
- [x] open-on-clear (y/n)
- [x] persistent-placeholder (y/n)
- [x] placeholder (string)
- [x] prefix (y/n)
- [x] prepend-inner-icon (icon)
- [x] reverse (y/n) 
- [x] rounded (y/n) 
- [x] shaped (y/n) 
- [x] small-chips (y/n) 
- [x] solo-inverted (y/n) 
- [x] suffix (y/n) 
- [x] validate-on-blur (y/n)

**Comment by MayaElf** [comment]
29 09 22 agreed not to implement - [ ] hide-spin-buttons (y/n) as it is a rare case when user is prohibited to use mouse-input

**Comment by MayaElf** [comment]
while checking the task a bug was detected in a new feature implementation. When we put some value into 'SHAPED' or 'Full width with ...' it automatically duplicates in all previous selectors. Comment from developer who did these features: 'The problem is in the names of variables. When coping pieces of code forgot to change names'.

**Comment by MayaElf** [comment]
Features implemented. Bugs fixed.
