### ISSUE TITLE
Angular rework: Elements to remove

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#4836]
Following elements do not exist in Angular version 15.6.2 (but do exist in JDI)
Please review them and make a decision if we have to keep it or remove or rename

1. DatepickerContainer
2. MaterialSelector
3. MaterialSelectorContainer
4. NativeSelector
5. NestedDropdownMenu
6. SortingOverview

**Comment by MayaElf** [comment]
Could you, please, clarify:
1) we should revise only classes in our jdi framework?
2) or there is some other source to review those elements

**Comment by FursovaKate** [comment]
Our test site doesn't contain these element's namings, however we do have unit tests for them. 
It seems like we shouldn't remove them, because the tests are checking the existing functionality:
DatepickerContainer - it's a general container for a DatePicker
MaterialSelector and MaterialSelectorContainer - are present on the test site under the Select element, but the unit test classes contain duplicate tests (including disabled duplicates), maybe we should think about joining these two classes, since both of them are testing the same functional for Select elements
NativeSelector - present on the test site under the Select element (Basic select)
NestedDropdownMenu - present on the test site under the Nested Menu element 
SortingOverview - present on the test site under the SORT HEADER element

**Comment by AlexeyGirin** [comment]
Done.
