### ISSUE TITLE
Remove "wrong" Button Group section and correct tests

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#722]
Remove "wrong" Button Group section and correct tests.
Check if documentation is correct and correct it as well

**Comment by a2313** [comment]
Please, revise the next sections:
1. Buttons (https://getbootstrap.com/docs/4.3/components/buttons/)
2. Alerts (https://getbootstrap.com/docs/4.3/components/alerts/)
3. Badge (https://getbootstrap.com/docs/4.3/components/badge/)
4. Caurosel (https://getbootstrap.com/docs/4.3/components/carousel/)
  and so on
because the text of the components and color is different from the components on Bootstrap documentation page and not all the possible styles are covered. That must be changed too

**Comment by AlexeyGirin** [comment]
Demo has been done.
