### ISSUE TITLE
Dowload driver always true

### ISSUE THREAD

**Issue by GhMartingit** [jdi-testing/jdi-light#74]
It  doesn't matter what value you set in Test.Properties file. Project always want to download driver.

![image](https://user-images.githubusercontent.com/42034349/52533526-68c5c000-2d4e-11e9-9c5c-2f9cb83fa552.png)

**Comment by AlexeyGirin** [comment]
Seems that GetLatest property is ignored, need consultation with @RomanIovlev

**Comment by BestNastos** [comment]
Property "driver.getLatest" doesn't exist. It's been replaced by property "drivers.version". 
In class DriverData line 73, default value of this (DRIVER_VERSION) property is "LATEST" which causes the problem in class DriverInfo line 37 method setupLocal(): "if" clause in the method is never used which means that custom driver, path to which is specified in "drivers.folder" is ignored, and driver always gets downloaded in "else" clause. 
Possible solution: make default DRIVER_VERSION value an empty string, but it should get a default value in case neither "drivers.version" nor "drivers.folder" is specified in properties (otherwise an exception will occur).

**Comment by antonfilichkin** [comment]
Pull request: [https://github.com/jdi-testing/jdi-light/pull/95](https://github.com/jdi-testing/jdi-light/pull/95)

Removed setting driver to latest by default. 

Expected framework behavior:

1. If **driver.version** is presented in property file - use (download if not presented) this driver.
2. If **driver.folder** is presented in property file - look for **chromedriver executable** in this location.
3. If both presented  - **driver.version** overrides **drivers.folder**
3. If neither is presented - look for **chromedriver executable** in **resources/drivers/** folder (set in project pom.file.
