### ISSUE TITLE
Syncronize JDropDown with DropDown in Java

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdi-light#94]
Droplist - custom dropdown implementation (annotated by @JDropdown) needs implementation in JDI-light-html, with possible usage of the same Dropdown Interface.
There is also need for @JMultiDropdown annotation to handle non-HTML5 implementations of MultiDropdowns (ex. Vegetables on Metals&Colors Page) or possibility to handle custom MultiDropdowns with @JDropdown annotation also.
Group of selectors are much the same - maybe it is better to solve this using one design.

As for current behavior:
It need to be synchronized with Dropdown.

    void select(int) - indexes from 0
    String selected() - method is not implemented
    is.selected(String) - assertion not working as in Dropdown
    is() (assertThat()) asserts needs calling expand() method to work as expected.
    (assertThat().values(contains("Colors", "Red", "Green", "Blue", "Yellow")))

Ask @antonfilichkin for more details

**Comment by RomanIovlev** [comment]
1. Droplist - unified implementation of any type of dropdown, multiselect, combobx etc. Any element that has 3 locators described in @JDropdown (value, list, expand)
This element is common and not related to jdi-light-html
2. @JMultiDropdown - we decide to not implement because it has the same locators as @JDropdown
3. MultiDropdowns - have no ideas about this type; vegetables have type MultiSelector
4. void select(int) - should be from 1 (fix in C# if this is wrong)
5. vegetables is not working at all - this is not standard element. Can be developed as Custom element in jdi-light-html-tests
